# Mapping of https://app.turvo.com/lobby/documentation#tag/Shipment
shipment_lookup_data = [
  {"type": "StopType", "code": "1500", "value": "Pickup"},
  {"type": "StopType", "code": "1501", "value": "Delivery"},
  {"type": "StopType", "code": "1502", "value": "Transload"},
  {"type": "StopType", "code": "1503", "value": "Storage"},
  {"type": "StopType", "code": "1506", "value": "Port of Landing"},
  {"type": "StopType", "code": "1507", "value": "Transshipment Port"},
  {"type": "StopType", "code": "1508", "value": "Recovery"},
  {"type": "StopType", "code": "1509", "value": "Termination"},
  {"type": "StopType", "code": "1515", "value": "Port of discharge"},

  {"type": "ShipmentStatus", "code": "2100", "value": "Quote active"},
  {"type": "ShipmentStatus", "code": "2101", "value": "Tendered"},
  {"type": "ShipmentStatus", "code": "2102", "value": "Covered"},
  {"type": "ShipmentStatus", "code": "2103", "value": "Dispatched"},
  {"type": "ShipmentStatus", "code": "2104", "value": "At pickup"},
  {"type": "ShipmentStatus", "code": "2105", "value": "En route"},
  {"type": "ShipmentStatus", "code": "2106", "value": "At delivery"},
  {"type": "ShipmentStatus", "code": "2107", "value": "Delivered"},
  {"type": "ShipmentStatus", "code": "2108", "value": "Ready for billing"},
  {"type": "ShipmentStatus", "code": "2109", "value": "Processing"},
  {"type": "ShipmentStatus", "code": "2110", "value": "Carrier paid"},
  {"type": "ShipmentStatus", "code": "2111", "value": "Customer paid"},
  {"type": "ShipmentStatus", "code": "2112", "value": "Completed"},
  {"type": "ShipmentStatus", "code": "2113", "value": "Canceled"},
  {"type": "ShipmentStatus", "code": "2114", "value": "Quote inactive"},
  {"type": "ShipmentStatus", "code": "2115", "value": "Picked up"},
  {"type": "ShipmentStatus", "code": "2116", "value": "Route Complete"},
  {"type": "ShipmentStatus", "code": "2117", "value": "Tender - offered"},
  {"type": "ShipmentStatus", "code": "2118", "value": "Tender - accepted"},
  {"type": "ShipmentStatus", "code": "2119", "value": "Tender - rejected"},
  {"type": "ShipmentStatus", "code": "2120", "value": "Draft"},
  {"type": "ShipmentStatus", "code": "2121", "value": "Shipment Ready"},
  {"type": "ShipmentStatus", "code": "2123", "value": "Acquiring Location"},
  {"type": "ShipmentStatus", "code": "2124", "value": "Customs Hold"},
  {"type": "ShipmentStatus", "code": "2125", "value": "Arrived"},
  {"type": "ShipmentStatus", "code": "2126", "value": "Available"},
  {"type": "ShipmentStatus", "code": "2127", "value": "Out Gated"},
  {"type": "ShipmentStatus", "code": "2129", "value": "In Gated"},
  {"type": "ShipmentStatus", "code": "2131", "value": "Arriving to Port"},
  {"type": "ShipmentStatus", "code": "2132", "value": "Berthing"},
  {"type": "ShipmentStatus", "code": "2133", "value": "Unloading"},
  {"type": "ShipmentStatus", "code": "2134", "value": "Ramped"},
  {"type": "ShipmentStatus", "code": "2135", "value": "Deramped"},
  {"type": "ShipmentStatus", "code": "2136", "value": "Departed"},
  {"type": "ShipmentStatus", "code": "2137", "value": "Held"},
  {"type": "ShipmentStatus", "code": "2138", "value": "Out for Delivery"},
  {"type": "ShipmentStatus", "code": "2139", "value": "In TransShipment"},
  {"type": "ShipmentStatus", "code": "2140", "value": "On Hold"},

  {"type": "CostType", "code": "1611", "value": "Accessorial - cross dock"},
  {"type": "CostType", "code": "1612", "value": "Accessorial - detention"},
  {"type": "CostType", "code": "1613", "value": "Accessorial - drayage"},
  {"type": "CostType", "code": "1614", "value": "Accessorial - extra miles"},
  {"type": "CostType", "code": "1615", "value": "Accessorial - layover"},
  {"type": "CostType", "code": "1616", "value": "Accessorial - loading"},
  {"type": "CostType", "code": "1617", "value": "Accessorial - lumper"},
  {"type": "CostType", "code": "1618", "value": "Accessorial - pallets"},
  {"type": "CostType", "code": "1619", "value": "Accessorial - stops"},
  {"type": "CostType", "code": "1620", "value": "Accessorial - storage"},
  {"type": "CostType", "code": "1621", "value": "Accessorial - tarp"},
  {"type": "CostType", "code": "1622", "value": "Accessorial - team services"},
  {"type": "CostType", "code": "1623", "value": "Accessorial - tolls"},
  {"type": "CostType", "code": "1624", "value": "Accessorial - trailer cleaning"},
  {"type": "CostType", "code": "1625", "value": "Accessorial - TWIC services"},
  {"type": "CostType", "code": "1626", "value": "Accessorial - unloading"},
  {"type": "CostType", "code": "1636", "value": "Accessorial - restack"},
  {"type": "CostType", "code": "23014", "value": "Accessorial - origin terminal handling charge"},
  {"type": "CostType", "code": "23015", "value": "Accessorial - destination terminal handling charge"},
  {"type": "CostType", "code": "23016", "value": "Accessorial - demurrage and detention"},
  {"type": "CostType", "code": "23017", "value": "Accessorial - origin reefer plug-in"},
  {"type": "CostType", "code": "23018", "value": "Accessorial - destination reefer plug-in"},
  {"type": "CostType", "code": "160200", "value": "Accessorial - Accessorial Charge"},
  {"type": "CostType", "code": "160201", "value": "Accessorial - Additional charge"},
  {"type": "CostType", "code": "160202", "value": "Accessorial - Bulkhead"},
  {"type": "CostType", "code": "160203", "value": "Accessorial - CARB Compliance Fee"},
  {"type": "CostType", "code": "160204", "value": "Accessorial - Charged as Weight"},
  {"type": "CostType", "code": "160205", "value": "Accessorial - Deficit Charge"},
  {"type": "CostType", "code": "160206", "value": "Accessorial - Excessive Length"},
  {"type": "CostType", "code": "160207", "value": "Accessorial - Forklift"},
  {"type": "CostType", "code": "160208", "value": "Accessorial - High Cost Delivery"},
  {"type": "CostType", "code": "160209", "value": "Accessorial - Redelivery Fee"},
  {"type": "CostType", "code": "160210", "value": "Accessorial - Refrigerate"},
  {"type": "CostType", "code": "160211", "value": "Accessorial - Requires Signature"},
  {"type": "CostType", "code": "160212", "value": "Accessorial - Unknown Charge"},
  {"type": "CostType", "code": "160213", "value": "Accessorial - Weekend Delivery"},
  {"type": "CostType", "code": "160214", "value": "Accessorial - Weekend Pickup"},
  {"type": "CostType", "code": "160215", "value": "Accessorial - Weight Fee - reweigh"},
  {"type": "CostType", "code": "160216", "value": "Accessorial - White Glove Service"},
  {"type": "CostType", "code": "160221", "value": "Location - Airport Delivery"},
  {"type": "CostType", "code": "160222", "value": "Location - Airport Pickup"},
  {"type": "CostType", "code": "160223", "value": "Location - Camp Delivery"},
  {"type": "CostType", "code": "160224", "value": "Location - Camp Pickup"},
  {"type": "CostType", "code": "160225", "value": "Location - Church Delivery"},
  {"type": "CostType", "code": "160226", "value": "Location - Church Pickup"},
  {"type": "CostType", "code": "160227", "value": "Location - Commercial Delivery"},
  {"type": "CostType", "code": "160228", "value": "Location - Commercial Pickup"},
  {"type": "CostType", "code": "160229", "value": "Location - Construction Site Delivery"},
  {"type": "CostType", "code": "160230", "value": "Location - Construction Site Pickup"},
  {"type": "CostType", "code": "160231", "value": "Location - Convention/Tradeshow Delivery"},
  {"type": "CostType", "code": "160232", "value": "Location - Convention/Tradeshow Pickup"},
  {"type": "CostType", "code": "160233", "value": "Location - Country Club Delivery"},
  {"type": "CostType", "code": "160234", "value": "Location - Country Club Pickup"},
  {"type": "CostType", "code": "160235", "value": "Location - Fair/Amusement/Park Delivery"},
  {"type": "CostType", "code": "160236", "value": "Location - Fair/Amusement/Park Pickup"},
  {"type": "CostType", "code": "160237", "value": "Location - Farm Delivery"},
  {"type": "CostType", "code": "160238", "value": "Location - Farm Pickup"},
  {"type": "CostType", "code": "160239", "value": "Location - Government Site Delivery"},
  {"type": "CostType", "code": "160240", "value": "Location - Government Site Pickup"},
  {"type": "CostType", "code": "160241", "value": "Location - Grocery Warehouse Delivery"},
  {"type": "CostType", "code": "160242", "value": "Location - Grocery Warehouse Pickup"},
  {"type": "CostType", "code": "160243", "value": "Location - Hospital Delivery"},
  {"type": "CostType", "code": "160244", "value": "Location - Hospital Pickup"},
  {"type": "CostType", "code": "160245", "value": "Location - Hotel Delivery"},
  {"type": "CostType", "code": "160246", "value": "Location - Hotel Pickup"},
  {"type": "CostType", "code": "160247", "value": "Location - Mall Delivery"},
  {"type": "CostType", "code": "160248", "value": "Location - Mall Pickup"},
  {"type": "CostType", "code": "160249", "value": "Location - Military Installation Delivery"},
  {"type": "CostType", "code": "160250", "value": "Location - Military Installation Pickup"},
  {"type": "CostType", "code": "160251", "value": "Harmonized Sales Tax"},
  {"type": "CostType", "code": "160252", "value": "Mine Site Delivery"},
  {"type": "CostType", "code": "160253", "value": "Mine Site Pickup"},
  {"type": "CostType", "code": "160254", "value": "Native American Reservation Delivery"},
  {"type": "CostType", "code": "160255", "value": "Native American Reservation Pickup"},
  {"type": "CostType", "code": "160256", "value": "Nursing Home Delivery"},
  {"type": "CostType", "code": "160257", "value": "Nursing Home Pickup"},
  {"type": "CostType", "code": "160258", "value": "Prison Delivery"},
  {"type": "CostType", "code": "160259", "value": "Prison Pickup"},
  {"type": "CostType", "code": "160260", "value": "Resort Delivery"},
  {"type": "CostType", "code": "160261", "value": "Resort Pickup"},
  {"type": "CostType", "code": "160262", "value": "School Delivery"},
  {"type": "CostType", "code": "160263", "value": "School Pickup"},
  {"type": "CostType", "code": "accessorial.other", "value": "Accessorial - Other"},
  {"type": "CostType", "code": "1640", "value": "Accessorial - white glove"},
  {"type": "CostType", "code": "1641", "value": "Accessorial - bonded shipment"},
  {"type": "CostType", "code": "1642", "value": "Accessorial - border crossing"},
  {"type": "CostType", "code": "1643", "value": "Accessorial - chassis"},
  {"type": "CostType", "code": "1644", "value": "Accessorial - crane"},
  {"type": "CostType", "code": "1645", "value": "Accessorial - delivery charge"},
  {"type": "CostType", "code": "1646", "value": "Accessorial - demurrage"},
  {"type": "CostType", "code": "1647", "value": "Accessorial - driver assistance"},
  {"type": "CostType", "code": "1648", "value": "Accessorial - drop trailer"},
  {"type": "CostType", "code": "1649", "value": "Accessorial - escort"},
  {"type": "CostType", "code": "1650", "value": "Accessorial - expedited"},
  {"type": "CostType", "code": "1651", "value": "Accessorial - farm"},
  {"type": "CostType", "code": "1652", "value": "Accessorial - freeze protect"},
  {"type": "CostType", "code": "1653", "value": "Accessorial - hook up"},
  {"type": "CostType", "code": "1654", "value": "Accessorial - insurance"},
  {"type": "CostType", "code": "1655", "value": "Accessorial - liftgate"},
  {"type": "CostType", "code": "1656", "value": "Accessorial - limited access"},
  {"type": "CostType", "code": "1657", "value": "Accessorial - oversized"},
  {"type": "CostType", "code": "1658", "value": "Accessorial - overweight"},
  {"type": "CostType", "code": "1659", "value": "Accessorial - permit"},
  {"type": "CostType", "code": "25100", "value": "Accessorial - chassis split"},
  {"type": "CostType", "code": "1660", "value": "Accessorial - rebill"},
  {"type": "CostType", "code": "25101", "value": "Accessorial - detention (loading)"},
  {"type": "CostType", "code": "1661", "value": "Accessorial - reclass"},
  {"type": "CostType", "code": "25102", "value": "Accessorial - detention (unloading)"},
  {"type": "CostType", "code": "1662", "value": "Accessorial - reconsignment"},
  {"type": "CostType", "code": "25103", "value": "Accessorial - per diem"},
  {"type": "CostType", "code": "1663", "value": "Accessorial - redelivery"},
  {"type": "CostType", "code": "25104", "value": "Accessorial - tri-axle"},
  {"type": "CostType", "code": "1664", "value": "Accessorial - repossession"},
  {"type": "CostType", "code": "1665", "value": "Accessorial - residential"},
  {"type": "CostType", "code": "1666", "value": "Accessorial - reweigh"},
  {"type": "CostType", "code": "1667", "value": "Accessorial - scale"},
  {"type": "CostType", "code": "1668", "value": "Accessorial - school"},
  {"type": "CostType", "code": "1669", "value": "Accessorial - service area surcharge"},
  {"type": "CostType", "code": "1670", "value": "Accessorial - shunting"},
  {"type": "CostType", "code": "1671", "value": "Accessorial - single shipment"},
  {"type": "CostType", "code": "1672", "value": "Accessorial - tow"},
  {"type": "CostType", "code": "1673", "value": "Accessorial - tracking"},
  {"type": "CostType", "code": "1674", "value": "Accessorial - transload"},
  {"type": "CostType", "code": "1675", "value": "Accessorial - weekend"},
  {"type": "CostType", "code": "25105", "value": "Accessorial - pre-pull"},
  {"type": "CostType", "code": "23006", "value": "Accessorial - capacity surcharge"},
  {"type": "CostType", "code": "23007", "value": "Accessorial - shipment restraints"},
  {"type": "CostType", "code": "1683", "value": "Accessorial - delivery appointment"},
  {"type": "CostType", "code": "1687", "value": "Accessorial - hazmat"},
  {"type": "CostType", "code": "1691", "value": "Accessorial - notify before arrival"},
  {"type": "CostType", "code": "1696", "value": "Accessorial - temperature controlled"},
  {"type": "CostType", "code": "1680", "value": "Accessorial - after hours"},
  {"type": "CostType", "code": "1684", "value": "Accessorial - driver count"},
  {"type": "CostType", "code": "1688", "value": "Accessorial - holiday"},
  {"type": "CostType", "code": "1693", "value": "Accessorial - pickup appointment"},
  {"type": "CostType", "code": "1697", "value": "Accessorial - tradeshow"},
  {"type": "CostType", "code": "1681", "value": "Accessorial - bobtail"},
  {"type": "CostType", "code": "1685", "value": "Accessorial - empty return"},
  {"type": "CostType", "code": "1689", "value": "Accessorial - inside delivery"},
  {"type": "CostType", "code": "1694", "value": "Accessorial - small truck"},
  {"type": "CostType", "code": "1682", "value": "Accessorial - deadhead"},
  {"type": "CostType", "code": "1686", "value": "Accessorial - guaranteed"},
  {"type": "CostType", "code": "1690", "value": "Accessorial - inside pickup"},
  {"type": "CostType", "code": "1695", "value": "Accessorial - sort and segregate"},
  {"type": "CostType", "code": "25268", "value": "Accessorial - Customs or In-bond freight charge"},
  {"type": "CostType", "code": "25339", "value": "Accessorial - Port customs paperwork processing"},
  {"type": "CostType", "code": "1606", "value": "Freight - per ton"},
  {"type": "CostType", "code": "1607", "value": "Freight - per tote"},
  {"type": "CostType", "code": "1608", "value": "Freight - per unit"},
  {"type": "CostType", "code": "23008", "value": "Freight - per hour"},
  {"type": "CostType", "code": "23022", "value": "Freight - per kg"},
  {"type": "CostType", "code": "23023", "value": "Freight - per kilometer"},
  {"type": "CostType", "code": "160217", "value": "Freight - Line Haul Surcharge"},
  {"type": "CostType", "code": "160218", "value": "Freight - Linehaul"},
  {"type": "CostType", "code": "160219", "value": "Freight - Minimum Charge"},
  {"type": "CostType", "code": "160220", "value": "Freight - Item"},
  {"type": "CostType", "code": "23003", "value": "Freight - per pallet"},
  {"type": "CostType", "code": "23004", "value": "Freight - per case"},
  {"type": "CostType", "code": "1601", "value": "Freight - per mile"},
  {"type": "CostType", "code": "1602", "value": "Freight - per bag"},
  {"type": "CostType", "code": "1600", "value": "Freight - flat"},
  {"type": "CostType", "code": "1603", "value": "Freight - per box"},
  {"type": "CostType", "code": "1604", "value": "Freight - per 50 lbs"},
  {"type": "CostType", "code": "1605", "value": "Freight - per 100 lbs"},
  {"type": "CostType", "code": "1609", "value": "Fuel - flat"},
  {"type": "CostType", "code": "1610", "value": "Fuel - per mile"},
  {"type": "CostType", "code": "23019", "value": "Fuel - bunker adjustment"},
  {"type": "CostType", "code": "23024", "value": "Fuel - per kilometer"},
  {"type": "CostType", "code": "23002", "value": "Fuel - percent of freight"},
  {"type": "CostType", "code": "23005", "value": "Fuel - percentage"},
  {"type": "CostType", "code": "1627", "value": "Other - advance fee"},
  {"type": "CostType", "code": "1628", "value": "Other - canceled shipment"},
  {"type": "CostType", "code": "1629", "value": "Other - claim"},
  {"type": "CostType", "code": "1630", "value": "Other - credit card fee"},
  {"type": "CostType", "code": "1631", "value": "Other - documentation"},
  {"type": "CostType", "code": "1632", "value": "Other - gate fee"},
  {"type": "CostType", "code": "1633", "value": "Other - late truck"},
  {"type": "CostType", "code": "1634", "value": "Other - payment adjustment"},
  {"type": "CostType", "code": "1635", "value": "Other - product issue"},
  {"type": "CostType", "code": "1637", "value": "Other"},
  {"type": "CostType", "code": "23009", "value": "Other - food grade"},
  {"type": "CostType", "code": "23010", "value": "Other - documentation fees"},
  {"type": "CostType", "code": "23011", "value": "Other - pre-carriage"},
  {"type": "CostType", "code": "23012", "value": "Other - on-carriage"},
  {"type": "CostType", "code": "23013", "value": "Other - IMO surcharge"},
  {"type": "CostType", "code": "1638", "value": "Other - discount"},
  {"type": "CostType", "code": "23020", "value": "Total planned cost"},
  {"type": "CostType", "code": "1676", "value": "Other - payment fee"},
  {"type": "CostType", "code": "1677", "value": "Other - processing fee"},
  {"type": "CostType", "code": "1678", "value": "Other - tax"},
  {"type": "CostType", "code": "1679", "value": "Other - truck ordered not used"},
  {"type": "CostType", "code": "25106", "value": "Other - Claim Expense"},
  {"type": "CostType", "code": "23025", "value": "Service - per kg"},
  {"type": "CostType", "code": "23026", "value": "Service - per kilometer"},
  {"type": "CostType", "code": "1698", "value": "Service - flat"},
  {"type": "CostType", "code": "1699", "value": "Service - per mile"},
  {"type": "CostType", "code": "23000", "value": "Service - per 100 lbs"},
  {"type": "CostType", "code": "23001", "value": "Service - per stop"},
  {"type": "CostType", "code": "23021", "value": "Tax - VAT"},

  {"type": "Units", "code": "6025", "value": "MT"},
  {"type": "Units", "code": "6024", "value": "kegs"},
  {"type": "Units", "code": "6022", "value": "cases"},
  {"type": "Units", "code": "6023", "value": "truckload"},
  {"type": "Units", "code": "6000", "value": "pallets"},
  {"type": "Units", "code": "6001", "value": "boxes"},
  {"type": "Units", "code": "6002", "value": "loose"},
  {"type": "Units", "code": "6003", "value": "bags"},
  {"type": "Units", "code": "6004", "value": "bales"},
  {"type": "Units", "code": "6005", "value": "bundles"},
  {"type": "Units", "code": "6006", "value": "cans"},
  {"type": "Units", "code": "6007", "value": "carboys"},
  {"type": "Units", "code": "6008", "value": "carpets"},
  {"type": "Units", "code": "6009", "value": "cartons"},
  {"type": "Units", "code": "6010", "value": "coils"},
  {"type": "Units", "code": "6011", "value": "crates"},
  {"type": "Units", "code": "6012", "value": "cylinders"},
  {"type": "Units", "code": "6013", "value": "drums"},
  {"type": "Units", "code": "6014", "value": "pails"},
  {"type": "Units", "code": "6015", "value": "reels"},
  {"type": "Units", "code": "6016", "value": "rolls"},
  {"type": "Units", "code": "6017", "value": "skids"},
  {"type": "Units", "code": "6018", "value": "totes"},
  {"type": "Units", "code": "6019", "value": "tubes/pipes"},
  {"type": "Units", "code": "6020", "value": "vehicles"},
  {"type": "Units", "code": "6021", "value": "other"},

  {"type": "ShipmentType", "code": "5000", "value": "FTL"},
  {"type": "ShipmentType", "code": "5001", "value": "LTL"},
  {"type": "FrieghtClass", "code": "5100", "value": "50"},
  {"type": "FrieghtClass", "code": "5101", "value": "55"},
  {"type": "FrieghtClass", "code": "5102", "value": "60"},
  {"type": "FrieghtClass", "code": "5103", "value": "65"},
  {"type": "FrieghtClass", "code": "5104", "value": "70"},
  {"type": "FrieghtClass", "code": "5105", "value": "77.5"},
  {"type": "FrieghtClass", "code": "5106", "value": "85"},
  {"type": "FrieghtClass", "code": "5107", "value": "92.5"},
  {"type": "FrieghtClass", "code": "5108", "value": "100"},
  {"type": "FrieghtClass", "code": "5109", "value": "110"},
  {"type": "FrieghtClass", "code": "5110", "value": "125"},
  {"type": "FrieghtClass", "code": "5111", "value": "150"},
  {"type": "FrieghtClass", "code": "5112", "value": "175"},
  {"type": "FrieghtClass", "code": "5113", "value": "200"},
  {"type": "FrieghtClass", "code": "5114", "value": "250"},
  {"type": "FrieghtClass", "code": "5115", "value": "300"},
  {"type": "FrieghtClass", "code": "5116", "value": "400"},
  {"type": "FrieghtClass", "code": "5117", "value": "500"},

  {"type": "SchedulingType", "code": "9400", "value": "FCFS(firstcome,firstserved"},
  {"type": "SchedulingType", "code": "9401", "value": "Byappointment"},
  {"type": "ExternalIdType", "code": "1406", "value": "Container #"},
  {"type": "ExternalIdType", "code": "1407", "value": "Order #"},
  {"type": "ExternalIdType", "code": "1400", "value": "Purchase order #"},
  {"type": "ExternalIdType", "code": "1401", "value": "Reference #"},
  {"type": "ExternalIdType", "code": "1402", "value": "BOL #"},
  {"type": "ExternalIdType", "code": "1403", "value": "PRO #"},
  {"type": "ExternalIdType", "code": "1404", "value": "Tracking #"},
  {"type": "ExternalIdType", "code": "1405", "value": "Other #"},

  {"type": "ItemCategory", "code": "22300", "value": "Other"},
  {"type": "ItemCategory", "code": "22301", "value": "Vehicle"},

  {"type": "CarrierPaymentType", "code": "1700", "value": "Paper check"},
  {"type": "CarrierPaymentType", "code": "1701", "value": "COMCHEK"},
  {"type": "CarrierPaymentType", "code": "1702", "value": "ACH"},
  {"type": "CarrierPaymentType", "code": "1703", "value": "Factoring company"},
  {"type": "CarrierPaymentType", "code": "1704", "value": "EFS"},
  {"type": "CarrierPaymentType", "code": "1705", "value": "Wire"},

  {"type": "CustomerPaymentType", "code": "9500", "value": "Paper check"},
  {"type": "CustomerPaymentType", "code": "9501", "value": "ACH"},
  {"type": "CustomerPaymentType", "code": "9502", "value": "Wire"},

  {"type": "CarrierPayTerms", "code": "7000", "value": "Standard 28 days"},
  {"type": "CarrierPayTerms", "code": "7001", "value": "5 days quick pay"},
  {"type": "CarrierPayTerms", "code": "7002", "value": "1 day quick pay"},

  {"type": "CustomerPayTerms", "code": "7100", "value": "Standard 15 days"},
  {"type": "CustomerPayTerms", "code": "7101", "value": "30 days"},
  {"type": "CustomerPayTerms", "code": "7102", "value": "45 days"},

  {"type": "PickupServices", "code": "21300", "value": "Driver count"},
  {"type": "PickupServices", "code": "21301", "value": "Driver load"},
  {"type": "PickupServices", "code": "21302", "value": "Inside pickup"},
  {"type": "PickupServices", "code": "21303", "value": "Liftgate"},
  {"type": "PickupServices", "code": "21304", "value": "Residential"},
  {"type": "PickupServices", "code": "21305", "value": "Hook trailer"},
  {"type": "PickupServices", "code": "21306", "value": "Unhook trailer"},
  {"type": "PickupServices", "code": "21307", "value": "After hours"},
  {"type": "PickupServices", "code": "21308", "value": "Detention"},
  {"type": "PickupServices", "code": "21309", "value": "Detention with power"},
  {"type": "PickupServices", "code": "21310", "value": "Detention without power"},
  {"type": "PickupServices", "code": "21311", "value": "Drayage"},
  {"type": "PickupServices", "code": "21312", "value": "Driver assistance"},
  {"type": "PickupServices", "code": "21313", "value": "Driver layover"},
  {"type": "PickupServices", "code": "21314", "value": "Drop trailer"},
  {"type": "PickupServices", "code": "21315", "value": "Escort"},
  {"type": "PickupServices", "code": "21316", "value": "Holiday"},
  {"type": "PickupServices", "code": "21317", "value": "Layover"},
  {"type": "PickupServices", "code": "21318", "value": "Limited access"},
  {"type": "PickupServices", "code": "21319", "value": "Loading"},
  {"type": "PickupServices", "code": "21320", "value": "Lumper"},
  {"type": "PickupServices", "code": "21321", "value": "Notify before arrival"},
  {"type": "PickupServices", "code": "21322", "value": "Permit"},
  {"type": "PickupServices", "code": "21323", "value": "Pickup appointment"},
  {"type": "PickupServices", "code": "21324", "value": "Reconsignment"},
  {"type": "PickupServices", "code": "21325", "value": "Storage"},
  {"type": "PickupServices", "code": "21326", "value": "Tradeshow"},
  {"type": "PickupServices", "code": "21327", "value": "TWIC services"},
  {"type": "PickupServices", "code": "21328", "value": "Weekend"},
  {"type": "PickupServices", "code": "21495", "value": "Dangerous Goods"},
  {"type": "PickupServices", "code": "21496", "value": "Hazmat"},
  {"type": "PickupServices", "code": "21497", "value": "Over Dimensions"},
  {"type": "PickupServices", "code": "21498", "value": "COD"},
  {"type": "PickupServices", "code": "21499", "value": "Guaranteed"},
  {"type": "PickupServices", "code": "21520", "value": "Guaranteed AM"},
  {"type": "PickupServices", "code": "21521", "value": "Urgent"},
  {"type": "PickupServices", "code": "21522", "value": "Stackable"},
  {"type": "PickupServices", "code": "21523", "value": "Bulkhead"},
  {"type": "PickupServices", "code": "21524", "value": "Expedited"},
  {"type": "PickupServices", "code": "21525", "value": "Certificate of Origin"},
  {"type": "PickupServices", "code": "21526", "value": "Express"},
  {"type": "PickupServices", "code": "21527", "value": "Deferred"},
  {"type": "PickupServices", "code": "21528", "value": "Standard"},
  {"type": "PickupServices", "code": "21529", "value": "Signature Required"},
  {"type": "PickupServices", "code": "21530", "value": "HAL"},
  {"type": "PickupServices", "code": "21531", "value": "Team Driver"},
  {"type": "PickupServices", "code": "21532", "value": "Backhaul"},
  {"type": "PickupServices", "code": "21533", "value": "WHS"},
  {"type": "PickupServices", "code": "21534", "value": "GOI"},
  {"type": "PickupServices", "code": "21561", "value": "NMC"},
  {"type": "PickupServices", "code": "21535", "value": "Saturday Pickup"},
  {"type": "PickupServices", "code": "21536", "value": "Holiday Pickup"},
  {"type": "PickupServices", "code": "21563", "value": "Sort and segregate"},
  {"type": "PickupServices", "code": "21564", "value": "Pallet jack"},
  {"type": "PickupServices", "code": "21565", "value": "Pickup Marking and Tagging"},
  {"type": "PickupServices", "code": "21566", "value": "NYC Metro"},
  {"type": "PickupServices", "code": "21567", "value": "Airport Pickup"},
  {"type": "PickupServices", "code": "21568", "value": "Camp Pickup"},
  {"type": "PickupServices", "code": "21569", "value": "Container Freight Station Pickup"},
  {"type": "PickupServices", "code": "21570", "value": "Church Pickup"},
  {"type": "PickupServices", "code": "21571", "value": "Country Club Pickup"},
  {"type": "PickupServices", "code": "21572", "value": "Convention/Tradeshow Pickup"},
  {"type": "PickupServices", "code": "21573", "value": "Construction Site Pickup"},
  {"type": "PickupServices", "code": "21574", "value": "Dock Pickup"},
  {"type": "PickupServices", "code": "21575", "value": "School Pickup"},
  {"type": "PickupServices", "code": "21576", "value": "Farm Pickup"},
  {"type": "PickupServices", "code": "21577", "value": "Government Site Pickup"},
  {"type": "PickupServices", "code": "21578", "value": "Grocery Warehouse Pickup"},
  {"type": "PickupServices", "code": "21579", "value": "Hospital Pickup"},
  {"type": "PickupServices", "code": "21580", "value": "Hotel Pickup"},
  {"type": "PickupServices", "code": "21581", "value": "Military Installation Pickup"},
  {"type": "PickupServices", "code": "21582", "value": "Mine Site Pickup"},
  {"type": "PickupServices", "code": "21583", "value": "Native American Reservation Pickup"},
  {"type": "PickupServices", "code": "21584", "value": "Non-Business Hours Pickup"},
  {"type": "PickupServices", "code": "21585", "value": "Nursing Home Pickup"},
  {"type": "PickupServices", "code": "21586", "value": "Fair/Amusement/Park Pickup"},
  {"type": "PickupServices", "code": "21587", "value": "Pier Pickup"},
  {"type": "PickupServices", "code": "21588", "value": "Prison Pickup"},
  {"type": "PickupServices", "code": "21589", "value": "Self-Storage Pickup"},
  {"type": "PickupServices", "code": "21590", "value": "Utility Site Pickup"},
  {"type": "PickupServices", "code": "21591", "value": "Mini-Storage Pickup"},
  {"type": "PickupServices", "code": "21592", "value": "Farm Country Club Estate Pickup"},
  {"type": "PickupServices", "code": "21593", "value": "Driver secure"},
  {"type": "PickupServices", "code": "21594", "value": "Exclusive use trailer"},
  {"type": "PickupServices", "code": "21595", "value": "Tanker Endorsement"},
  {"type": "PickupServices", "code": "21596", "value": "Coil Racks"},
  {"type": "PickupServices", "code": "21597", "value": "Edge Protectors"},
  {"type": "PickupServices", "code": "21598", "value": "Chain Protectors"},
  {"type": "PickupServices", "code": "21599", "value": "Ramps"},
  {"type": "PickupServices", "code": "21770", "value": "AirRide"},
  {"type": "PickupServices", "code": "21771", "value": "PPE safety gear"},
  {"type": "PickupServices", "code": "21772", "value": "Straps"},
  {"type": "PickupServices", "code": "21773", "value": "GPS tracking"},
  {"type": "PickupServices", "code": "21774", "value": "Heavy lifting"},
  {"type": "PickupServices", "code": "21775", "value": "Load levelers"},
  {"type": "PickupServices", "code": "21776", "value": "Pipe stakes & dunnage"},
  {"type": "PickupServices", "code": "21777", "value": "Transloading"},
  {"type": "PickupServices", "code": "21778", "value": "Winch"},
  {"type": "PickupServices", "code": "21779", "value": "Upper deck ramps"},
  {"type": "PickupServices", "code": "21780", "value": "Bumper pull"},
  {"type": "PickupServices", "code": "21781", "value": "Driver load/unload"},
  {"type": "PickupServices", "code": "21782", "value": "Temporary tags"},
  {"type": "PickupServices", "code": "21783", "value": "Trailer Hitch Connection Type:Pintle"},
  {"type": "PickupServices", "code": "21784", "value": "Trailer Hitch Connection Type:Ball"},
  {"type": "PickupServices", "code": "21785", "value": "Brakes Type:Air"},
  {"type": "PickupServices", "code": "21786", "value": "Brakes Type:Electric"},
  {"type": "PickupServices", "code": "21787", "value": "Enclosed Trailer"},
  {"type": "PickupServices", "code": "21788", "value": "Tarps"},
  {"type": "PickupServices", "code": "21735", "value": "Pipe Stakes"},
  {"type": "PickupServices", "code": "21731", "value": "Dunnage"},
  {"type": "PickupServices", "code": "21789", "value": "Driver Takedown"},
  {"type": "PickupServices", "code": "21790", "value": "Tow Takedown"},
  {"type": "PickupServices", "code": "21791", "value": "Driver Setup/Install"},
  {"type": "PickupServices", "code": "21792", "value": "Tow Setup/Install"},
  {"type": "PickupServices", "code": "21793", "value": "Loading and Local Pickup"},
  {"type": "PickupServices", "code": "21794", "value": "Unloading"},
  {"type": "PickupServices", "code": "21795", "value": "Unloading and Local Delivery"},
  {"type": "PickupServices", "code": "21796", "value": "Trip Charge"},
  {"type": "PickupServices", "code": "21797", "value": "On-Site relocation"},
  {"type": "PickupServices", "code": "21798", "value": "Block and Brace"},
  {"type": "PickupServices", "code": "21800", "value": "Dock height"},
  {"type": "PickupServices", "code": "21801", "value": "Pre-pull"},
  {"type": "PickupServices", "code": "21802", "value": "Chassis"},
  {"type": "PickupServices", "code": "21803", "value": "Chassis Split"},
  {"type": "PickupServices", "code": "21804", "value": "Chassis Flip"},
  {"type": "PickupServices", "code": "21805", "value": "Tri-axle"},
  {"type": "PickupServices", "code": "21806", "value": "Dry-run"},
  {"type": "PickupServices", "code": "21807", "value": "Refrigerated"},

  {"type": "DeliveryServices", "code": "21400", "value": "Driver count"},
  {"type": "DeliveryServices", "code": "21401", "value": "Driver unload"},
  {"type": "DeliveryServices", "code": "21402", "value": "Inside delivery"},
  {"type": "DeliveryServices", "code": "21403", "value": "Liftgate"},
  {"type": "DeliveryServices", "code": "21404", "value": "Residential"},
  {"type": "DeliveryServices", "code": "21405", "value": "Unhook trailer"},
  {"type": "DeliveryServices", "code": "21406", "value": "Hook trailer"},
  {"type": "DeliveryServices", "code": "21407", "value": "Delivery Appointment"},
  {"type": "DeliveryServices", "code": "21408", "value": "After hours"},
  {"type": "DeliveryServices", "code": "21409", "value": "Detention"},
  {"type": "DeliveryServices", "code": "21410", "value": "Detention with power"},
  {"type": "DeliveryServices", "code": "21411", "value": "Detention without power"},
  {"type": "DeliveryServices", "code": "21412", "value": "Drayage"},
  {"type": "DeliveryServices", "code": "21413", "value": "Driver assistance"},
  {"type": "DeliveryServices", "code": "21414", "value": "Driver layover"},
  {"type": "DeliveryServices", "code": "21415", "value": "Drop trailer"},
  {"type": "DeliveryServices", "code": "21416", "value": "Escort"},
  {"type": "DeliveryServices", "code": "21417", "value": "Holiday"},
  {"type": "DeliveryServices", "code": "21418", "value": "Layover"},
  {"type": "DeliveryServices", "code": "21419", "value": "Limited access"},
  {"type": "DeliveryServices", "code": "21420", "value": "Lumper"},
  {"type": "DeliveryServices", "code": "21421", "value": "Notify before arrival"},
  {"type": "DeliveryServices", "code": "21422", "value": "Permit"},
  {"type": "DeliveryServices", "code": "21423", "value": "Reconsignment"},
  {"type": "DeliveryServices", "code": "21424", "value": "Redelivery"},
  {"type": "DeliveryServices", "code": "21425", "value": "Storage"},
  {"type": "DeliveryServices", "code": "21426", "value": "Tradeshow"},
  {"type": "DeliveryServices", "code": "21427", "value": "TWIC services"},
  {"type": "DeliveryServices", "code": "21428", "value": "Unloading"},
  {"type": "DeliveryServices", "code": "21429", "value": "Weekend"},
  {"type": "DeliveryServices", "code": "21450", "value": "Dangerous Goods"},
  {"type": "DeliveryServices", "code": "21451", "value": "Hazmat"},
  {"type": "DeliveryServices", "code": "21452", "value": "Over Dimensions"},
  {"type": "DeliveryServices", "code": "21453", "value": "COD"},
  {"type": "DeliveryServices", "code": "21454", "value": "Guaranteed"},
  {"type": "DeliveryServices", "code": "21455", "value": "Guaranteed AM"},
  {"type": "DeliveryServices", "code": "21456", "value": "Urgent"},
  {"type": "DeliveryServices", "code": "21457", "value": "Stackable"},
  {"type": "DeliveryServices", "code": "21458", "value": "Bulkhead"},
  {"type": "DeliveryServices", "code": "21459", "value": "Expedited"},
  {"type": "DeliveryServices", "code": "21460", "value": "Certificate of Origin"},
  {"type": "DeliveryServices", "code": "21461", "value": "Express"},
  {"type": "DeliveryServices", "code": "21462", "value": "Deferred"},
  {"type": "DeliveryServices", "code": "21463", "value": "Standard"},
  {"type": "DeliveryServices", "code": "21464", "value": "Signature Required"},
  {"type": "DeliveryServices", "code": "21465", "value": "HAL"},
  {"type": "DeliveryServices", "code": "21466", "value": "Team Driver"},
  {"type": "DeliveryServices", "code": "21467", "value": "Backhaul"},
  {"type": "DeliveryServices", "code": "21468", "value": "WHS"},
  {"type": "DeliveryServices", "code": "21560", "value": "NMC"},
  {"type": "DeliveryServices", "code": "21469", "value": "GOI"},
  {"type": "DeliveryServices", "code": "21471", "value": "Saturday Delivery"},
  {"type": "DeliveryServices", "code": "21472", "value": "Holiday Delivery"},
  {"type": "DeliveryServices", "code": "21610", "value": "Sort and segregate"},
  {"type": "DeliveryServices", "code": "21611", "value": "Pallet jack"},
  {"type": "DeliveryServices", "code": "21612", "value": "Delivery marking and tagging"},
  {"type": "DeliveryServices", "code": "21613", "value": "NYC metro"},
  {"type": "DeliveryServices", "code": "21614", "value": "Airport delivery"},
  {"type": "DeliveryServices", "code": "21615", "value": "Camp delivery"},
  {"type": "DeliveryServices", "code": "21616", "value": "Container freight station delivery"},
  {"type": "DeliveryServices", "code": "21617", "value": "Church delivery"},
  {"type": "DeliveryServices", "code": "21618", "value": "Country club delivery"},
  {"type": "DeliveryServices", "code": "21619", "value": "Convention/Tradeshow Delivery"},
  {"type": "DeliveryServices", "code": "21620", "value": "Construction Site Delivery"},
  {"type": "DeliveryServices", "code": "21621", "value": "Distribution Center Delivery"},
  {"type": "DeliveryServices", "code": "21622", "value": "Dock Delivery"},
  {"type": "DeliveryServices", "code": "21623", "value": "School delivery"},
  {"type": "DeliveryServices", "code": "21624", "value": "Farm delivery"},
  {"type": "DeliveryServices", "code": "21625", "value": "Government Site Delivery"},
  {"type": "DeliveryServices", "code": "21626", "value": "Grocery Warehouse Delivery"},
  {"type": "DeliveryServices", "code": "21627", "value": "Hospital Delivery"},
  {"type": "DeliveryServices", "code": "21628", "value": "Hotel Delivery"},
  {"type": "DeliveryServices", "code": "21629", "value": "Mall Delivery"},
  {"type": "DeliveryServices", "code": "21630", "value": "Military Installation Delivery"},
  {"type": "DeliveryServices", "code": "21631", "value": "Mine Site Delivery"},
  {"type": "DeliveryServices", "code": "21632", "value": "Native American Reservation Delivery"},
  {"type": "DeliveryServices", "code": "21633", "value": "Non-Business Hours Delivery"},
  {"type": "DeliveryServices", "code": "21634", "value": "Non-Commercial Delivery"},
  {"type": "DeliveryServices", "code": "21635", "value": "Nursing Home Delivery"},
  {"type": "DeliveryServices", "code": "21636", "value": "Fair/Amusement/Park Delivery"},
  {"type": "DeliveryServices", "code": "21637", "value": "Pier Delivery"},
  {"type": "DeliveryServices", "code": "21638", "value": "Prison Delivery"},
  {"type": "DeliveryServices", "code": "21639", "value": "Resort Delivery"},
  {"type": "DeliveryServices", "code": "21640", "value": "Self-Storage Delivery"},
  {"type": "DeliveryServices", "code": "21641", "value": "Sunday Delivery"},
  {"type": "DeliveryServices", "code": "21642", "value": "Utility Site Delivery"},
  {"type": "DeliveryServices", "code": "21643", "value": "Mini-Storage Delivery"},
  {"type": "DeliveryServices", "code": "21644", "value": "Farm Country Club Estate Delivery"},
  {"type": "DeliveryServices", "code": "21645", "value": "Driver secure"},
  {"type": "DeliveryServices", "code": "21646", "value": "Exclusive use trailer"},
  {"type": "DeliveryServices", "code": "21647", "value": "Tanker Endorsement"},
  {"type": "DeliveryServices", "code": "21648", "value": "Coil Racks"},
  {"type": "DeliveryServices", "code": "21649", "value": "Edge Protectors"},
  {"type": "DeliveryServices", "code": "21650", "value": "Chain Protectors"},
  {"type": "DeliveryServices", "code": "21710", "value": "Ramps"},
  {"type": "DeliveryServices", "code": "21711", "value": "AirRide"},
  {"type": "DeliveryServices", "code": "21712", "value": "PPE safety gear"},
  {"type": "DeliveryServices", "code": "21713", "value": "Straps"},
  {"type": "DeliveryServices", "code": "21714", "value": "GPS tracking"},
  {"type": "DeliveryServices", "code": "21715", "value": "Heavy lifting"},
  {"type": "DeliveryServices", "code": "21716", "value": "Load levelers"},
  {"type": "DeliveryServices", "code": "21717", "value": "Pipe stakes & dunnage"},
  {"type": "DeliveryServices", "code": "21718", "value": "Transloading"},
  {"type": "DeliveryServices", "code": "21719", "value": "Winch"},
  {"type": "DeliveryServices", "code": "21720", "value": "Upper deck ramps"},
  {"type": "DeliveryServices", "code": "21721", "value": "Bumper pull"},
  {"type": "DeliveryServices", "code": "21722", "value": "Driver load/unload"},
  {"type": "DeliveryServices", "code": "21723", "value": "Temporary tags"},
  {"type": "DeliveryServices", "code": "21724", "value": "Trailer Hitch Connection Type:Pintle"},
  {"type": "DeliveryServices", "code": "21725", "value": "Trailer Hitch Connection Type:Ball"},
  {"type": "DeliveryServices", "code": "21726", "value": "Brakes Type:Air"},
  {"type": "DeliveryServices", "code": "21727", "value": "Brakes Type:Electric"},
  {"type": "DeliveryServices", "code": "21728", "value": "Enclosed Trailer"},
  {"type": "DeliveryServices", "code": "21729", "value": "Tarps"},
  {"type": "DeliveryServices", "code": "21730", "value": "Dunnage"},
  {"type": "DeliveryServices", "code": "21734", "value": "Pipe Stakes"},
  {"type": "DeliveryServices", "code": "31738", "value": "Driver Takedown"},
  {"type": "DeliveryServices", "code": "31739", "value": "Tow Takedown"},
  {"type": "DeliveryServices", "code": "31740", "value": "Driver Setup/Install"},
  {"type": "DeliveryServices", "code": "31741", "value": "Tow Setup/Install"},
  {"type": "DeliveryServices", "code": "31742", "value": "Loading and Local Pickup"},
  {"type": "DeliveryServices", "code": "31744", "value": "Unloading and Local Delivery"},
  {"type": "DeliveryServices", "code": "31745", "value": "Trip Charge"},
  {"type": "DeliveryServices", "code": "31746", "value": "On-Site relocation"},
  {"type": "DeliveryServices", "code": "31747", "value": "Block and Brace"},
  {"type": "DeliveryServices", "code": "31749", "value": "Dock height"},
  {"type": "DeliveryServices", "code": "31750", "value": "Pre-pull"},
  {"type": "DeliveryServices", "code": "31751", "value": "Chassis"},
  {"type": "DeliveryServices", "code": "31752", "value": "Chassis Split"},
  {"type": "DeliveryServices", "code": "31753", "value": "Chassis Flip"},
  {"type": "DeliveryServices", "code": "31754", "value": "Tri-axle"},
  {"type": "DeliveryServices", "code": "31755", "value": "Dry-run"},
  {"type": "DeliveryServices", "code": "31756", "value": "Refrigerated"},

  {"type": "EquipmentServices", "code": "21200", "value": "Hazmat"},
  {"type": "EquipmentServices", "code": "21201", "value": "Oversized"},
  {"type": "EquipmentServices", "code": "21202", "value": "Protect from freeze"},
  {"type": "EquipmentServices", "code": "21203", "value": "Sort and segregate"},
  {"type": "EquipmentServices", "code": "21204", "value": "Team"},
  {"type": "EquipmentServices", "code": "21205", "value": "White glove"},
  {"type": "EquipmentServices", "code": "21206", "value": "Bobtail"},
  {"type": "EquipmentServices", "code": "21207", "value": "Bonded shipment"},
  {"type": "EquipmentServices", "code": "21208", "value": "Border crossing"},
  {"type": "EquipmentServices", "code": "21209", "value": "Chasis per diem"},
  {"type": "EquipmentServices", "code": "21210", "value": "Deadhead"},
  {"type": "EquipmentServices", "code": "21211", "value": "Drayage"},
  {"type": "EquipmentServices", "code": "21212", "value": "Driver assistance"},
  {"type": "EquipmentServices", "code": "21213", "value": "Driver count"},
  {"type": "EquipmentServices", "code": "21214", "value": "Drop trailer"},
  {"type": "EquipmentServices", "code": "21215", "value": "Empty return"},
  {"type": "EquipmentServices", "code": "21216", "value": "Escort"},
  {"type": "EquipmentServices", "code": "21217", "value": "Expedited"},
  {"type": "EquipmentServices", "code": "21218", "value": "Extra miles"},
  {"type": "EquipmentServices", "code": "21219", "value": "Guaranteed"},
  {"type": "EquipmentServices", "code": "21220", "value": "Insurance"},
  {"type": "EquipmentServices", "code": "21221", "value": "Liftgate"},
  {"type": "EquipmentServices", "code": "21222", "value": "Overweight"},
  {"type": "EquipmentServices", "code": "21223", "value": "Pallets"},
  {"type": "EquipmentServices", "code": "21224", "value": "Permit"},
  {"type": "EquipmentServices", "code": "21225", "value": "Reconsignment"},
  {"type": "EquipmentServices", "code": "21226", "value": "Reweigh"},
  {"type": "EquipmentServices", "code": "21227", "value": "Scale"},
  {"type": "EquipmentServices", "code": "21228", "value": "Service area surcharge"},
  {"type": "EquipmentServices", "code": "21229", "value": "Shipment restraints"},
  {"type": "EquipmentServices", "code": "21230", "value": "Single shipment"},
  {"type": "EquipmentServices", "code": "21231", "value": "Small truck"},
  {"type": "EquipmentServices", "code": "21232", "value": "Stop off"},
  {"type": "EquipmentServices", "code": "21233", "value": "Storage"},
  {"type": "EquipmentServices", "code": "21234", "value": "Tarp"},
  {"type": "EquipmentServices", "code": "21235", "value": "Temperature controlled"},
  {"type": "EquipmentServices", "code": "21236", "value": "Trailer cleaning"},
  {"type": "EquipmentServices", "code": "21237", "value": "Truck ordered not used"},
  {"type": "EquipmentServices", "code": "21238", "value": "TWIC services"},
  {"type": "EquipmentServices", "code": "21239", "value": "Other"},
  {"type": "EquipmentServices", "code": "21240", "value": "Chains"},
  {"type": "EquipmentServices", "code": "21241", "value": "Curtains"},
  {"type": "EquipmentServices", "code": "21242", "value": "Hotshot"},
  {"type": "EquipmentServices", "code": "21243", "value": "Pallet jack"},
  {"type": "EquipmentServices", "code": "21244", "value": "Tarps"},
  {"type": "EquipmentServices", "code": "21245", "value": "Exclusive use trailer"},
  {"type": "EquipmentServices", "code": "21246", "value": "Tanker endorsement"},
  {"type": "EquipmentServices", "code": "21247", "value": "Coil racks"},
  {"type": "EquipmentServices", "code": "21248", "value": "Edge protectors"},
  {"type": "EquipmentServices", "code": "21249", "value": "Chain protectors"},
  {"type": "EquipmentServices", "code": "21250", "value": "Ramps"},
  {"type": "EquipmentServices", "code": "21251", "value": "AirRide"},
  {"type": "EquipmentServices", "code": "21252", "value": "PPE safety gear"},
  {"type": "EquipmentServices", "code": "21253", "value": "Straps"},
  {"type": "EquipmentServices", "code": "21254", "value": "GPS tracking"},
  {"type": "EquipmentServices", "code": "21255", "value": "Heavy lifting"},
  {"type": "EquipmentServices", "code": "21256", "value": "Load levelers"},
  {"type": "EquipmentServices", "code": "21257", "value": "Pipe stakes and dunnage"},
  {"type": "EquipmentServices", "code": "21258", "value": "Transloading"},
  {"type": "EquipmentServices", "code": "21259", "value": "Upper deck ramps"},
  {"type": "EquipmentServices", "code": "21260", "value": "Bumper pull"},
  {"type": "EquipmentServices", "code": "21261", "value": "Driver load/unload"},
  {"type": "EquipmentServices", "code": "21262", "value": "Temporary tags"},
  {"type": "EquipmentServices", "code": "21263", "value": "Time definite"},
  {"type": "EquipmentServices", "code": "21264", "value": "Weight Determination"},
  {"type": "EquipmentServices", "code": "21265", "value": "Blind shipment"},
  {"type": "EquipmentServices", "code": "21266", "value": "Blanket service"},
  {"type": "EquipmentServices", "code": "21267", "value": "Stackable"},
  {"type": "EquipmentServices", "code": "21268", "value": "Turnkey"},
  {"type": "EquipmentServices", "code": "21269", "value": "Food grade products"},
  {"type": "EquipmentServices", "code": "21270", "value": "Restricted delivery"},
  {"type": "EquipmentServices", "code": "21271", "value": "Shipper release"},
  {"type": "EquipmentServices", "code": "21272", "value": "Second man"},
  {"type": "EquipmentServices", "code": "21273", "value": "Proactive response"},
  {"type": "EquipmentServices", "code": "21274", "value": "Shipment hold"},
  {"type": "EquipmentServices", "code": "21275", "value": "Tanker endorsed driver"},
  {"type": "EquipmentServices", "code": "21276", "value": "Holiday pickup"},
  {"type": "EquipmentServices", "code": "21277", "value": "Holiday delivery"},
  {"type": "EquipmentServices", "code": "21278", "value": "Signature required"},
  {"type": "EquipmentServices", "code": "21279", "value": "Saturday delivery"},
  {"type": "EquipmentServices", "code": "21280", "value": "Arbitrary charge"},
  {"type": "EquipmentServices", "code": "21281", "value": "Inbound shipment"},
  {"type": "EquipmentServices", "code": "21282", "value": "Northbound Canadian border crossing document handling fee"},
  {"type": "EquipmentServices", "code": "21283", "value": "Capacity load"},
  {"type": "EquipmentServices", "code": "21284", "value": "Change of BOL"},
  {"type": "EquipmentServices", "code": "21285", "value": "COD"},
  {"type": "EquipmentServices", "code": "21286", "value": "Redelivery"},
  {"type": "EquipmentServices", "code": "21287", "value": "Excessive value"},
  {"type": "EquipmentServices", "code": "21288", "value": "Export shipment"},
  {"type": "EquipmentServices", "code": "21289", "value": "Freezable"},
  {"type": "EquipmentServices", "code": "21290", "value": "Home move service"},
  {"type": "EquipmentServices", "code": "21291", "value": "Import shipment"},
  {"type": "EquipmentServices", "code": "21292", "value": "Interline shipment"},
  {"type": "EquipmentServices", "code": "21293", "value": "Inter-regional shipment"},
  {"type": "EquipmentServices", "code": "21294", "value": "Lumper"},
  {"type": "EquipmentServices", "code": "21295", "value": "Over 750, Under 6"},
  {"type": "EquipmentServices", "code": "21296", "value": "Over dimensions"},
  {"type": "EquipmentServices", "code": "21297", "value": "Protect from heat"},
  {"type": "EquipmentServices", "code": "21298", "value": "Regional shipment"},
  {"type": "EquipmentServices", "code": "21299", "value": "Port Customs Paperwork Processing"},
  {"type": "EquipmentServices", "code": "21665", "value": "Marking and Tagging"},
  {"type": "EquipmentServices", "code": "21666", "value": "Security Inspection"},
  {"type": "EquipmentServices", "code": "21667", "value": "Weight Inspection"},
  {"type": "EquipmentServices", "code": "21668", "value": "Hawaiian Will Call"},
  {"type": "EquipmentServices", "code": "21669", "value": "Inside pickup"},
  {"type": "EquipmentServices", "code": "21670", "value": "Inside delivery"},
  {"type": "EquipmentServices", "code": "21671", "value": "Winch"},
  {"type": "EquipmentServices", "code": "21672", "value": "Trailer Hitch Connection Type:Pintle"},
  {"type": "EquipmentServices", "code": "21673", "value": "Trailer Hitch Connection Type:Ball"},
  {"type": "EquipmentServices", "code": "21674", "value": "Brakes Type:Air"},
  {"type": "EquipmentServices", "code": "21675", "value": "Brakes Type:Electric"},
  {"type": "EquipmentServices", "code": "21676", "value": "Enclosed Trailer"},
  {"type": "EquipmentServices", "code": "21737", "value": "Pipe Stakes"},
  {"type": "EquipmentServices", "code": "21733", "value": "Dunnage"},
  {"type": "EquipmentServices", "code": "21738", "value": "Driver Takedown"},
  {"type": "EquipmentServices", "code": "21739", "value": "Tow Takedown"},
  {"type": "EquipmentServices", "code": "21740", "value": "Driver Setup/Install"},
  {"type": "EquipmentServices", "code": "21741", "value": "Tow Setup/Install"},
  {"type": "EquipmentServices", "code": "21742", "value": "Loading and Local Pickup"},
  {"type": "EquipmentServices", "code": "21743", "value": "Unloading"},
  {"type": "EquipmentServices", "code": "21744", "value": "Unloading and Local Delivery"},
  {"type": "EquipmentServices", "code": "21745", "value": "Trip Charge"},
  {"type": "EquipmentServices", "code": "21746", "value": "Labor"},
  {"type": "EquipmentServices", "code": "21747", "value": "On-site Relocation"},
  {"type": "EquipmentServices", "code": "21748", "value": "Block and Brace"},
  {"type": "EquipmentServices", "code": "21750", "value": "Dock height"},
  {"type": "EquipmentServices", "code": "21751", "value": "Pre-pull"},
  {"type": "EquipmentServices", "code": "21752", "value": "Chassis"},
  {"type": "EquipmentServices", "code": "21753", "value": "Chassis Split"},
  {"type": "EquipmentServices", "code": "21754", "value": "Chassis Flip"},
  {"type": "EquipmentServices", "code": "21755", "value": "Tri-axle"},
  {"type": "EquipmentServices", "code": "21756", "value": "Dry-run"},
  {"type": "EquipmentServices", "code": "21757", "value": "Refrigerated"},

  {"type": "TrackingMethod", "code": "31300", "value": "None"},
  {"type": "TrackingMethod", "code": "31301", "value": "Turvo Driver app"},

  {"type": "PaymentTerms", "code": "21503", "value": "Prepaid"},
  {"type": "PaymentTerms", "code": "21504", "value": "Collect"},
  {"type": "PaymentTerms", "code": "21505", "value": "Third Party"},

  {"type": "FreightPaymentTerms", "code": "freightpaymentterms.pp", "value": "Prepaid"},
  {"type": "FreightPaymentTerms", "code": "freightpaymentterms.collect", "value": "Collect"},
  {"type": "FreightPaymentTerms", "code": "freightpaymentterms.thirdparty", "value": "Third Party"},

  {"type": "ReasonCode", "code": "37300", "value": "Missed Delivery(A1)"},
  {"type": "ReasonCode", "code": "37301", "value": "Incorrect Address(A2)"},
  {"type": "ReasonCode", "code": "37302", "value": "Indirect Delivery(A3)"},
  {"type": "ReasonCode", "code": "37303", "value": "Unable to Locate(A5)"},
  {"type": "ReasonCode", "code": "37304", "value": "Address Corrected - Delivery Attempted(A6)"},
  {"type": "ReasonCode", "code": "37305", "value": "Mis-sort(AA)"},
  {"type": "ReasonCode", "code": "37306", "value": "Customer Requested Future Delivery(AD)"},
  {"type": "ReasonCode", "code": "37307", "value": "Restricted Articles Unacceptable(AE)"},
  {"type": "ReasonCode", "code": "37308", "value": "Accident(AF)"},
  {"type": "ReasonCode", "code": "37309", "value": "Consignee Related(AG)"},
  {"type": "ReasonCode", "code": "37310", "value": "Driver Related(AH)"},
  {"type": "ReasonCode", "code": "37311", "value": "Mechanical Breakdown(AI)"},
  {"type": "ReasonCode", "code": "37312", "value": "Other Carrier Related(AJ)"},
  {"type": "ReasonCode", "code": "37313", "value": "Damaged, Rewrapped in Hub(AK)"},
  {"type": "ReasonCode", "code": "37314", "value": "Previous Stop(AL)"},
  {"type": "ReasonCode", "code": "37315", "value": "Shipper Related(AM)"},
  {"type": "ReasonCode", "code": "37316", "value": "Holiday - Closed(AN)"},
  {"type": "ReasonCode", "code": "37317", "value": "Weather or Natural Disaster Related(AO)"},
  {"type": "ReasonCode", "code": "37318", "value": "Awaiting Export(AP)"},
  {"type": "ReasonCode", "code": "37319", "value": "Recipient Unavailable - Delivery Delayed(AQ)"},
  {"type": "ReasonCode", "code": "37320", "value": "Improper International Paperwork(AR)"},
  {"type": "ReasonCode", "code": "37321", "value": "Hold Due to Customs Documentation Problems(AS)"},
  {"type": "ReasonCode", "code": "37322", "value": "Unable to Contact Recipient for Broker Information(AT)"},
  {"type": "ReasonCode", "code": "37323", "value": "Civil Event Related Delay(AU)"},
  {"type": "ReasonCode", "code": "37324", "value": "Exceeds Service Limitations(AV)"},
  {"type": "ReasonCode", "code": "37325", "value": "Past Cut-off Time(AW)"},
  {"type": "ReasonCode", "code": "37326", "value": "Insufficient Pickup Time(AX)"},
  {"type": "ReasonCode", "code": "37327", "value": "Missed Pickup(AY)"},
  {"type": "ReasonCode", "code": "37328", "value": "Alternate Carrier Delivered(AZ)"},
  {"type": "ReasonCode", "code": "37329", "value": "Consignee Closed(B1)"},
  {"type": "ReasonCode", "code": "37330", "value": "Trap for Customer(B2)"},
  {"type": "ReasonCode", "code": "37331", "value": "Held for Payment(B4)"},
  {"type": "ReasonCode", "code": "37332", "value": "Held for Consignee(B5)"},
  {"type": "ReasonCode", "code": "37333", "value": "Improper Unloading Facility or Equipment(B8)"},
  {"type": "ReasonCode", "code": "37334", "value": "Receiving Time Restricted(B9)"},
  {"type": "ReasonCode", "code": "37335", "value": "Held per Shipper(BB)"},
  {"type": "ReasonCode", "code": "37336", "value": "Missing Documents(BC)"},
  {"type": "ReasonCode", "code": "37337", "value": "Border Clearance(BD)"},
  {"type": "ReasonCode", "code": "37338", "value": "Road Conditions(BE)"},
  {"type": "ReasonCode", "code": "37339", "value": "Carrier Keying Error(BF)"},
  {"type": "ReasonCode", "code": "37340", "value": "Other(BG)"},
  {"type": "ReasonCode", "code": "37341", "value": "Insufficient Time to Complete Delivery(BH)"},
  {"type": "ReasonCode", "code": "37342", "value": "Cartage Agent(BI)"},
  {"type": "ReasonCode", "code": "37343", "value": "Customer Wanted Earlier Delivery(BJ)"},
  {"type": "ReasonCode", "code": "37344", "value": "Prearranged Appointment(BK)"},
  {"type": "ReasonCode", "code": "37345", "value": "Held for Protective Service(BL)"},
  {"type": "ReasonCode", "code": "37346", "value": "Flatcar Shortage(BM)"},
  {"type": "ReasonCode", "code": "37347", "value": "Failed to Release Billing(BN)"},
  {"type": "ReasonCode", "code": "37348", "value": "Railroad Failed to Meet Schedule(BO)"},
  {"type": "ReasonCode", "code": "37349", "value": "Load Shifted(BP)"},
  {"type": "ReasonCode", "code": "37350", "value": "Shipment Overweight(BQ)"},
  {"type": "ReasonCode", "code": "37351", "value": "Train Derailment(BR)"},
  {"type": "ReasonCode", "code": "37352", "value": "Refused by Customer(BS)"},
  {"type": "ReasonCode", "code": "37353", "value": "Returned to Shipper(BT)"},
  {"type": "ReasonCode", "code": "37354", "value": "Waiting for Customer Pickup(C1)"},
  {"type": "ReasonCode", "code": "37355", "value": "Credit Hold(C2)"},
  {"type": "ReasonCode", "code": "37356", "value": "Suspended at Customer Request(C3)"},
  {"type": "ReasonCode", "code": "37357", "value": "Customer Vacation(C4)"},
  {"type": "ReasonCode", "code": "37358", "value": "Customer Strike(C5)"},
  {"type": "ReasonCode", "code": "37359", "value": "Waiting Shipping Instructions(C6)"},
  {"type": "ReasonCode", "code": "37360", "value": "Waiting for Customer Specified Carrier(C7)"},
  {"type": "ReasonCode", "code": "37361", "value": "Collect on Delivery Required(C8)"},
  {"type": "ReasonCode", "code": "37362", "value": "Cash Not Available From Consignee(C9)"},
  {"type": "ReasonCode", "code": "37363", "value": "Customs (Import or Export)(CA)"},
  {"type": "ReasonCode", "code": "37364", "value": "No Requested Arrival Date Provided by Shipper(CB)"},
  {"type": "ReasonCode", "code": "37365", "value": "No Requested Arrival Time Provided by Shipper(CC)"},
  {"type": "ReasonCode", "code": "37366", "value": "Carrier Dispatch Error(D1)"},
  {"type": "ReasonCode", "code": "37367", "value": "Driver Not Available(D2)"},
  {"type": "ReasonCode", "code": "37368", "value": "Non-Express Clearance Delay(F1)"},
  {"type": "ReasonCode", "code": "37369", "value": "International Non-carrier Delay(F2)"},
  {"type": "ReasonCode", "code": "37370", "value": "Held Pending Appointment(HB)"},
  {"type": "ReasonCode", "code": "37371", "value": "Processing Delay(P1)"},
  {"type": "ReasonCode", "code": "37372", "value": "Waiting Inspection(P2)"},
  {"type": "ReasonCode", "code": "37373", "value": "Production Falldown(P3)"},
  {"type": "ReasonCode", "code": "37374", "value": "Held for Full Carrier Load(P4)"},
  {"type": "ReasonCode", "code": "37375", "value": "Reconsigned(RC)"},
  {"type": "ReasonCode", "code": "37376", "value": "Delivery Shortage(S1)"},
  {"type": "ReasonCode", "code": "37377", "value": "Tractor With Sleeper Car Not Available(T1)"},
  {"type": "ReasonCode", "code": "37378", "value": "Tractor, Conventional, Not Available(T2)"},
  {"type": "ReasonCode", "code": "37379", "value": "Trailer not Available(T3)"},
  {"type": "ReasonCode", "code": "37380", "value": "Trailer Not Usable Due to Prior Product(T4)"},
  {"type": "ReasonCode", "code": "37381", "value": "Trailer Class Not Available(T5)"},
  {"type": "ReasonCode", "code": "37382", "value": "Trailer Volume Not Available(T6)"},
  {"type": "ReasonCode", "code": "37383", "value": "Insufficient Delivery Time(T7)"},
  {"type": "ReasonCode", "code": "37384", "value": "Normal Appointment(NA)"},
  {"type": "ReasonCode", "code": "37385", "value": "Normal Status(NS)"},
]

# Mapping of https://app.turvo.com/lobby/documentation#tag/Location
location_lookup_data = [
  {"type": "FacilityType", "code": "9400", "value": "FCFS (firstcome, firstserved)"},
  {"type": "FacilityType", "code": "9401", "value": "By appointment"},

  {"type": "Timezone", "code": "America/Los_Angeles", "value": "PST"},
  {"type": "Timezone", "code": "America/Detroit", "value": "EST"},
  {"type": "Timezone", "code": "America/Denver", "value": "MST"},
  {"type": "Timezone", "code": "America/Chicago", "value": "CST"},

  {"type": "LocationAddressType", "code": "1154", "value": "Other"},
  {"type": "LocationAddressType", "code": "1155", "value": "Billing"},
  {"type": "LocationAddressType", "code": "1151", "value": "Physical"},
  {"type": "LocationAddressType", "code": "1152", "value": "Safer"},
  {"type": "LocationAddressType", "code": "1153", "value": "Main"},

  {"type": "LocationEmailType", "code": "1061", "value": "Other"},
  {"type": "LocationEmailType", "code": "1062", "value": "Billing"},
  {"type": "LocationEmailType", "code": "1060", "value": "Main"},

  {"type": "LocationPhoneType", "code": "1073", "value": "AfterHours"},
  {"type": "LocationPhoneType", "code": "1074", "value": "Billing"},
  {"type": "LocationPhoneType", "code": "1072", "value": "Fax"},
  {"type": "LocationPhoneType", "code": "1070", "value": "Main"},
  {"type": "LocationPhoneType", "code": "1071", "value": "Other"}
]

# Mapping of https://app.turvo.com/lobby/documentation#tag/Customer
customer_lookup_data = [
  {"type": "CustomerAddressType", "code": "1160", "value": "Main"},
  {"type": "CustomerAddressType", "code": "1161", "value": "Billing"},
  {"type": "CustomerAddressType", "code": "1162", "value": "Work"},
  {"type": "CustomerAddressType", "code": "1163", "value": "Other"},

  {"type": "CustomerEmailType", "code": "1085", "value": "Main"},
  {"type": "CustomerEmailType", "code": "1086", "value": "Other"},
  {"type": "CustomerEmailType", "code": "1087", "value": "Billing"},

  {"type": "CustomerPhoneType", "code": "1010", "value": "Main"},
  {"type": "CustomerPhoneType", "code": "1011", "value": "Fax"},
  {"type": "CustomerPhoneType", "code": "1012", "value": "Afterhours"},
  {"type": "CustomerPhoneType", "code": "1013", "value": "Other"},
  {"type": "CustomerPhoneType", "code": "1014", "value": "Billing"},

  {"type": "CustomerPaymentType", "code": "9500", "value": "Paper check"},
  {"type": "CustomerPaymentType", "code": "9501", "value": "ACH"},
  {"type": "CustomerPaymentType", "code": "9502", "value": "Wire"},

  {"type": "CustomerPayTerms", "code": "7107", "value": "60days"},
  {"type": "CustomerPayTerms", "code": "7102", "value": "45days"},
  {"type": "CustomerPayTerms", "code": "7100", "value": "Standard 15 days"},
  {"type": "CustomerPayTerms", "code": "7101", "value": "days"},

  {"type": "CustomerStatus", "code": "2200", "value": "Created"},
  {"type": "CustomerStatus", "code": "2201", "value": "Prospect"},
  {"type": "CustomerStatus", "code": "2202", "value": "Active"},
  {"type": "CustomerStatus", "code": "2203", "value": "Inactive"},
  {"type": "CustomerStatus", "code": "2204", "value": "Suspended"},
]

# Mapping of https://app.turvo.com/lobby/documentation#tag/Carrier
carrier_lookup_data = [
  {"type": "CarrierAccountStatus", "code": "2250", "value": "Created"},
  {"type": "CarrierAccountStatus", "code": "2252", "value": "Active"},
  {"type": "CarrierAccountStatus", "code": "2253", "value": "Inactive"},
  {"type": "CarrierAccountStatus", "code": "2254", "value": "Suspended"},

  {"type": "CarrierAddressType", "code": "1143", "value": "Main"},
  {"type": "CarrierAddressType", "code": "1144", "value": "Other"},
  {"type": "CarrierAddressType", "code": "1140", "value": "Mailing"},
  {"type": "CarrierAddressType", "code": "1141", "value": "Physical"},
  {"type": "CarrierAddressType", "code": "1145", "value": "Billing"},
  {"type": "CarrierAddressType", "code": "1146", "value": "Claims"},

  {"type": "CarrierEmailType", "code": "1080", "value": "Main"},
  {"type": "CarrierEmailType", "code": "1081", "value": "Other"},
  {"type": "CarrierEmailType", "code": "1082", "value": "Billing"},
  {"type": "CarrierEmailType", "code": "1083", "value": "Claims"},

  {"type": "CarrierPhoneType", "code": "1020", "value": "Main"},
  {"type": "CarrierPhoneType", "code": "1021", "value": "Fax"},
  {"type": "CarrierPhoneType", "code": "1022", "value": "Afterhours"},
  {"type": "CarrierPhoneType", "code": "1023", "value": "Other"},
  {"type": "CarrierPhoneType", "code": "1024", "value": "Main"},
  {"type": "CarrierPhoneType", "code": "1025", "value": "Billing"},
  {"type": "CarrierPhoneType", "code": "1026", "value": "Claims"},

  {"type": "CarrierPayTerms", "code": "7000", "value": "Standard 28 days"},
  {"type": "CarrierPayTerms", "code": "7001", "value": "5 days quick pay"},
  {"type": "CarrierPayTerms", "code": "7002", "value": "1 day quick pay"},

  {"type": "InsuranceType", "code": "1800", "value": "Cargo"},
  {"type": "InsuranceType", "code": "1801", "value": "Liability"},
  {"type": "InsuranceType", "code": "1802", "value": "Refrigeration breakdown"},
  {"type": "InsuranceType", "code": "1803", "value": "Worker's compensation"},

  {"type": "EquipmentSize", "code": "1300", "value": "20ft"},
  {"type": "EquipmentSize", "code": "1301", "value": "24ft"},
  {"type": "EquipmentSize", "code": "1302", "value": "28ft"},
  {"type": "EquipmentSize", "code": "1303", "value": "40ft"},
  {"type": "EquipmentSize", "code": "1304", "value": "48ft"},
  {"type": "EquipmentSize", "code": "1305", "value": "50ft"},
  {"type": "EquipmentSize", "code": "1306", "value": "53ft"},
  {"type": "EquipmentSize", "code": "1307", "value": "Other"},

  {"type": "BankAccountType", "code": "1751", "value": "Savings"},
  {"type": "BankAccountType", "code": "1752", "value": "Checking"},

  {"type": "PaymentType", "code": "1700", "value": "Paper check"},
  {"type": "PaymentType", "code": "1701", "value": "COMCHEK"},
  {"type": "PaymentType", "code": "1702", "value": "ACH"},
  {"type": "PaymentType", "code": "1703", "value": "Factoring company"},
  {"type": "PaymentType", "code": "1704", "value": "EFS"},
  {"type": "PaymentType", "code": "1705", "value": "Wire"},
  {"type": "PaymentType", "code": "1707", "value": "PayPal"},
  {"type": "PaymentType", "code": "1708", "value": "Credit card"},
  {"type": "PaymentType", "code": "1709", "value": "Third Party"},

  {"type": "PayTermType", "code": "17700", "value": "Advance"},
  {"type": "PayTermType", "code": "17701", "value": "Regular"},

  {"type": "CarrierModeType", "code": "7200", "value": "FTL"},
  {"type": "CarrierModeType", "code": "7201", "value": "LTL"},
  {"type": "CarrierModeType", "code": "7202", "value": "Parcel"},
  {"type": "CarrierModeType", "code": "7203", "value": "Rail"},
  {"type": "CarrierModeType", "code": "7204", "value": "Ocean"},
  {"type": "CarrierModeType", "code": "7205", "value": "Air"},
  {"type": "CarrierModeType", "code": "7206", "value": "LCL"},
  {"type": "CarrierModeType", "code": "7207", "value": "Barge"},

  {"type": "CarrierServiceType", "code": "7300", "value": "Hazmat"},
  {"type": "CarrierServiceType", "code": "7301", "value": "Oversized"},
  {"type": "CarrierServiceType", "code": "7302", "value": "Drop trailer"},
  {"type": "CarrierServiceType", "code": "7303", "value": "Team"},
  {"type": "CarrierServiceType", "code": "7304", "value": "Last mile"},
  {"type": "CarrierServiceType", "code": "7305", "value": "In-store delivery"},
  {"type": "CarrierServiceType", "code": "7306", "value": "Airport access (TSA)"},
  {"type": "CarrierServiceType", "code": "7307", "value": "Port access (TWIC)"},
  {"type": "CarrierServiceType", "code": "7308", "value": "Power only"},
  {"type": "CarrierServiceType", "code": "7309", "value": "Hot shot"},
  {"type": "CarrierServiceType", "code": "7310", "value": "Expedited"},
  {"type": "CarrierServiceType", "code": "7311", "value": "SmartWay (EPA)"},
  {"type": "CarrierServiceType", "code": "7312", "value": "Intermodal (UIIA)"},
  {"type": "CarrierServiceType", "code": "7313", "value": "TRU refrigeration"},
  {"type": "CarrierServiceType", "code": "7314", "value": "Dispatch service"},
  {"type": "CarrierServiceType", "code": "7315", "value": "GPS tracking"},
]

# Mapping of https://app.turvo.com/lobby/documentation#tag/Order
order_lookup_data = [
  {"type": "OrderType", "code": "33095", "value": "Transportation order"},
  {"type": "OrderType", "code": "33096", "value": "Warehouse order"},
  {"type": "OrderType", "code": "33097", "value": "Customer order"},

  {"type": "TransportationOrderPhase", "code": "33041", "value": "Open"},
  {"type": "TransportationOrderPhase", "code": "33042", "value": "Plan"},
  {"type": "TransportationOrderPhase", "code": "33043", "value": "Ship"},
  {"type": "TransportationOrderPhase", "code": "33044", "value": "Bill"},
  {"type": "TransportationOrderPhase", "code": "33045", "value": "Complete"},
  {"type": "TransportationOrderPhase", "code": "33046", "value": "Cancel"},

  {"type": "WarehouseOrderPhase", "code": "33101", "value": "Open"},
  {"type": "WarehouseOrderPhase", "code": "33102", "value": "Plan"},
  {"type": "WarehouseOrderPhase", "code": "33103", "value": "Processing"},
  {"type": "WarehouseOrderPhase", "code": "33104", "value": "Closed"},
  {"type": "WarehouseOrderPhase", "code": "33105", "value": "Bill"},
  {"type": "WarehouseOrderPhase", "code": "33106", "value": "Canceled"},

  {"type": "CustomerOrderPhase", "code": "33124", "value": "Open"},
  {"type": "CustomerOrderPhase", "code": "33125", "value": "Plan"},
  {"type": "CustomerOrderPhase", "code": "33126", "value": "Processing"},
  {"type": "CustomerOrderPhase", "code": "33127", "value": "Closed"},
  {"type": "CustomerOrderPhase", "code": "33128", "value": "Bill"},

  {"type": "TransportationOrderStatus", "code": "33051", "value": "Draft"},
  {"type": "TransportationOrderStatus", "code": "33052", "value": "Submitted"},
  {"type": "TransportationOrderStatus", "code": "33053", "value": "Confirmed"},
  {"type": "TransportationOrderStatus", "code": "33054", "value": "Committed"},
  {"type": "TransportationOrderStatus", "code": "33055", "value": "Scheduled"},
  {"type": "TransportationOrderStatus", "code": "33056", "value": "Picking"},
  {"type": "TransportationOrderStatus", "code": "33057", "value": "Dispatched"},
  {"type": "TransportationOrderStatus", "code": "33058", "value": "At pickup"},
  {"type": "TransportationOrderStatus", "code": "33059", "value": "Picked up"},
  {"type": "TransportationOrderStatus", "code": "33060", "value": "En route"},
  {"type": "TransportationOrderStatus", "code": "33061", "value": "At delivery"},
  {"type": "TransportationOrderStatus", "code": "33062", "value": "Delivered"},
  {"type": "TransportationOrderStatus", "code": "33063", "value": "Route complete"},
  {"type": "TransportationOrderStatus", "code": "33064", "value": "Ready for billing"},
  {"type": "TransportationOrderStatus", "code": "33065", "value": "Processing"},
  {"type": "TransportationOrderStatus", "code": "33066", "value": "Carrier paid"},
  {"type": "TransportationOrderStatus", "code": "33067", "value": "Customer paid"},
  {"type": "TransportationOrderStatus", "code": "33068", "value": "Completed"},
  {"type": "TransportationOrderStatus", "code": "33069", "value": "Canceled"},

  {"type": "WarehouseOrderStatus", "code": "33111", "value": "Draft"},
  {"type": "WarehouseOrderStatus", "code": "33112", "value": "Submitted"},
  {"type": "WarehouseOrderStatus", "code": "33113", "value": "Confirmed"},
  {"type": "WarehouseOrderStatus", "code": "33114", "value": "Scheduled"},
  {"type": "WarehouseOrderStatus", "code": "33115", "value": "Committed"},
  {"type": "WarehouseOrderStatus", "code": "33116", "value": "Receiving"},
  {"type": "WarehouseOrderStatus", "code": "33117", "value": "Processing"},
  {"type": "WarehouseOrderStatus", "code": "33118", "value": "Loading"},
  {"type": "WarehouseOrderStatus", "code": "33119", "value": "Loaded"},
  {"type": "WarehouseOrderStatus", "code": "33120", "value": "Closed"},
  {"type": "WarehouseOrderStatus", "code": "33121", "value": "Bill"},
  {"type": "WarehouseOrderStatus", "code": "33122", "value": "Canceled"},
  {"type": "WarehouseOrderStatus", "code": "33123", "value": "Unloaded"},

  {"type": "CustomerOrderStatus", "code": "33130", "value": "Draft"},
  {"type": "CustomerOrderStatus", "code": "33131", "value": "Submitted"},
  {"type": "CustomerOrderStatus", "code": "33132", "value": "Confirmed"},
  {"type": "CustomerOrderStatus", "code": "33133", "value": "Scheduled"},
  {"type": "CustomerOrderStatus", "code": "33134", "value": "Committed"},
  {"type": "CustomerOrderStatus", "code": "33135", "value": "Receiving"},
  {"type": "CustomerOrderStatus", "code": "33136", "value": "Processing"},
  {"type": "CustomerOrderStatus", "code": "33137", "value": "Loading"},
  {"type": "CustomerOrderStatus", "code": "33138", "value": "Loaded"},
  {"type": "CustomerOrderStatus", "code": "33145", "value": "Unloaded"},
  {"type": "CustomerOrderStatus", "code": "33139", "value": "Closed"},
  {"type": "CustomerOrderStatus", "code": "33140", "value": "Bill"},
  {"type": "CustomerOrderStatus", "code": "33144", "value": "Canceled"},

  {"type": "OrderSubType", "code": "33001", "value": "Blanket"},
  {"type": "OrderSubType", "code": "33002", "value": "Relay"},

  {"type": "OrderDirectionType", "code": "33003", "value": "Inbound"},
  {"type": "OrderDirectionType", "code": "33004", "value": "Outbound"},
  {"type": "OrderDirectionType", "code": "33005", "value": "Transfer"},

  {"type": "StateLocationType", "code": "33014", "value": "OPEN"},
  {"type": "StateLocationType", "code": "33015", "value": "CLOSED"},

  {"type": "OrderDocumentType", "code": "33029", "value": "Order"},
  {"type": "OrderDocumentType", "code": "33030", "value": "Invoice"},
  {"type": "OrderDocumentType", "code": "33031", "value": "Other"},
  {"type": "OrderDocumentType", "code": "33035", "value": "Bill of lading"},

  {"type": "ExternalIdType", "code": "1400", "value": "Purchase order"},
  {"type": "ExternalIdType", "code": "1414", "value": "Sales order"},
  {"type": "ExternalIdType", "code": "1415", "value": "Warehouse order"},
  {"type": "ExternalIdType", "code": "1416", "value": "Service order"},
  {"type": "ExternalIdType", "code": "1405", "value": "Other"},
  {"type": "ExternalIdType", "code": "1407", "value": "Order"},

  {"type": "OrderTrailerStatus", "code": "33033", "value": "Live"},
  {"type": "OrderTrailerStatus", "code": "33034", "value": "Drop"},

  {"type": "RequestedDateType", "code": "33091", "value": "On a specific date"},
  {"type": "RequestedDateType", "code": "33092", "value": "Date range"},
]
